name: my_flutter_app
description: A new Flutter project.
environment:
  sdk: '>=3.4.0 <4.0.0'
analyzer:
  enable-experiment:
    - super-parameters
dependencies:
  flutter:
    sdk: flutter
  material: any  # Always use the latest available version
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.